package alchemyplusplus;

import alchemyplusplus.gui.GUIHandler;
import alchemyplusplus.proxy.CommonProxy;
import alchemyplusplus.utility.ConfigManager;
import alchemyplusplus.utility.EventManager;
import cpw.mods.fml.common.Mod;
import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.Mod.Instance;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.SidedProxy;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.network.NetworkRegistry;
import java.util.Arrays;

@Mod(modid = AlchemyPlusPlus.ID, name = AlchemyPlusPlus.NAME, version = AlchemyPlusPlus.VERSION_FULL, useMetadata = false,guiFactory = "alchemyplusplus.gui.GUIFactory", acceptedMinecraftVersions = "[1.7.10,)")
public class AlchemyPlusPlus
{

    // Internal name for referring to the mod
    public static final String ID = "alchemyplusplus";
    // Set channel name for use in NetworkMod
    public static final String CHANNEL_NAME = ID;

    // Human readible mod name
    public static final String NAME = "AlchemyPlusPlus";

    public static final String V_MAJOR = "@MAJOR@";
    public static final String V_MINOR = "@MINOR@";
    public static final String V_REVIS = "@REVIS@";
    public static final String V_BUILD = "@BUILD@";
    public static final String VERSION_FULL = V_MAJOR + "." + V_MINOR + "." + V_REVIS + "." + V_BUILD;

    // Texture basedir
    public static final String textureBase = "minechem:";

    // Instancing
    @Instance(value = CHANNEL_NAME)
    public static AlchemyPlusPlus INSTANCE;

    public static GUIHandler guiHandler = new GUIHandler();


    /*
     * Herbs addon loaded
     */
    public static boolean herbs = false;
    @Instance(value = "AlchemyPlusPlus")
    public static AlchemyPlusPlus instance = new AlchemyPlusPlus();
    @SidedProxy(clientSide = "alchemyplusplus.proxy.client.ClientProxy", serverSide = "alchemyplusplus.proxy.CommonProxy")
    public static CommonProxy proxy;

    @Mod.Metadata(AlchemyPlusPlus.ID)
    public static ModMetadata metadata;

    @EventHandler
    public void preInit(FMLInitializationEvent event)
    {
        INSTANCE = this;
        // Setup Mod Metadata for players to see in mod list with other mods.
        metadata.modId = AlchemyPlusPlus.ID;
        metadata.name = AlchemyPlusPlus.NAME;
        metadata.description = AlchemyPlusPlus.NAME + ": Feel the need to brew the perfect potion? Is the vanilla Minecraft brewing system to simple for your refined tastes? If so, AlchemyPlusPlus might be the mod for you";
        metadata.url = "http://www.minechemmod.com/";
        metadata.logoFile = "assets/" + AlchemyPlusPlus.ID + "/logo.png";
        metadata.version = V_MAJOR + "." + V_MINOR + "." + V_REVIS;
        metadata.authorList = Arrays.asList(new String[]
        {
            "jakimfett"
        });
        metadata.autogenerated = false;

        proxy.registerRenderers();
        proxy.registerTileEntitys();

        BlockRegistry.registerBlocks();
        ItemRegistry.registerItems();

        BlockRegistry.registerBlockRecipes();
        ItemRegistry.registerItemRecipes();

        // Book.loadAll();
        if (ConfigManager.appHardcoreModeEnabled)
        {
            ItemRegistry.registerHardcoreRecipes();
        }

        EventManager.registerEventHooks();
    }

    @EventHandler
    public void init(FMLInitializationEvent event)
    {
        NetworkRegistry.INSTANCE.registerGuiHandler(this, new GUIHandler());
    }

    @EventHandler
    public void postInit(FMLPostInitializationEvent event)
    {
    }

    @EventHandler
    public void preInit(FMLPreInitializationEvent event)
    {
        ConfigManager.initialSetup(event.getSuggestedConfigurationFile());

    }

}
